on:
  push:
    branches:
    - main

jobs:
  validate_and_trigger_jenkins_job:
    if: "!contains(github.event.head_commit.message, '[Jenkins]')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
